language: android
jdk: openjdk8
android:
  components:
    - android-28
    - build-tools-28.0.3
before_install:
  - chmod +x run_all_tests.sh
script:
  - ./run_all_tests.sh
env:
  global:
    - export ANDROID_SDK_ROOT=/usr/local/android-sdk